### ISSUE TITLE
react-wordcloud native?

### ISSUE THREAD

**Issue by warlock** [chrisrzhou/react-wordcloud#10]
In the future, do you have a version for reaccion-native (d3-svg)?

**Comment by chrisrzhou** [comment]
Hi @warlock, don't plan to build one for react native.  Is this as simple as swapping `d3` for `d3-svg`?

**Comment by warlock** [comment]
Probably. I Investigate when I return from a trip. I inform you soon.

**Comment by geminiyellow** [comment]
still working?
