### ISSUE TITLE
Words animation on every re -render

### ISSUE THREAD

**Issue by AliYar-Khan** [chrisrzhou/react-wordcloud#115]
I have explained the issue here in the video attached. Any help will be appreciated.

https://www.loom.com/share/5ffa4881b0b84ca9926cebeebd670e24?sid=b4cb175e-7b86-4fb4-9d45-1e8fa0fd2f23

**Comment by guilhermee098** [comment]
I think the video may no longer be accessible, but memoizing the component could be the solution.
