### ISSUE TITLE
Tooltip text

### ISSUE THREAD

**Issue by swrj** [chrisrzhou/react-wordcloud#13]
Is there any way of changing the text on the tooltip when you hover over it? I ideally want to use another field in data as the text.

**Comment by chrisrzhou** [comment]
Hi @swrj, you can do this by setting the `getWordTooltip` props (see documentation here: https://react-wordcloud.netlify.com/#/usage/callbacks)

Let me know if this works!

**Comment by swrj** [comment]
@chrisrzhou no idea how I missed that, thanks!
