### ISSUE TITLE
Not support Chinese?

### ISSUE THREAD

**Issue by beibm** [chrisrzhou/react-wordcloud#14]
It seems that the online demo not support Chinese！

**Comment by chrisrzhou** [comment]
Hi @beibm, I am using `docz` and `docz-default-theme` for the documentation.  Would be happy to accept a PR if multi-language support can be implemented in the `docz` layer.  If you have any ideas let me know!

**Comment by chrisrzhou** [comment]
Closing issue and happy for PRs that can solve this at the `docz` level.  The documentation is handled by `docz` using `mdx` file format.
