### ISSUE TITLE
Compatibility with Preact?

### ISSUE THREAD

**Issue by dandv** [chrisrzhou/react-wordcloud#15]
I've been trying to run the example from the README with Preact, but I'm running into [errors](https://github.com/developit/preact/issues/1247#issuecomment-494742024). Any ideas?

**Comment by chrisrzhou** [comment]
Hey @dandv, not too familiar with compatibility with Preact, but saw that you opened an issue on their side.  If you find the underlying issue, please let me know here, or submit a PR.

In the meantime, let me know if there're any other issues you see with the component and happy to address them in one version fix.

Thanks for checking this out!

**Comment by chrisrzhou** [comment]
Closing the issue since it seems related with preact in the other open issue.  Please feel free to reopen the issue again in the future!
