### ISSUE TITLE
Reduce bundle size?

### ISSUE THREAD

**Issue by dandv** [chrisrzhou/react-wordcloud#16]
Not sure how practical this is given the dependencies but...

https://bundlephobia.com/result?p=react-wordcloud@1.0.5

**Comment by chrisrzhou** [comment]
Hi @dandv, I can look into reducing this in 1.0.6 sometime this week, while polishing up some of the Typescript errors. `react-wordcloud` uses `d3` very lightly, so it's possible to drop that dependency entirely.

**Comment by chrisrzhou** [comment]
Hi @dandv, I broke out the `d3` dependencies in v1.0.6, and the package size is [roughly halved](https://bundlephobia.com/scan-results?packages=@types/d3-array@2.0.0,@types/d3-cloud@1.2.2,@types/d3-scale@2.1.1,@types/d3-scale-chromatic@1.3.1,@types/d3-selection@1.4.1,@types/d3-transition@1.1.4,@types/seedrandom@2.4.28,d3-array@2.2.0,d3-cloud@1.2.5,d3-scale@3.0.0,d3-scale-chromatic@1.3.3,d3-selection@1.4.0,d3-transition@1.2.0,resize-observer-polyfill@1.5.1,seedrandom@3.0.1,tippy.js@4.3.4).  Thanks for raising this up! When v1.0.6 is captured in bundlephobia later, you can check again.  Closing the issue!
