### ISSUE TITLE
Unsafe eval issue

### ISSUE THREAD

**Issue by kraiyons** [chrisrzhou/react-wordcloud#19]
Hello, i am experiencing this issue when I use `react-wordcloud`. I'm afraid I can't use the meta tag work around for other reasons, is there any other solution for this?

![image](https://user-images.githubusercontent.com/14866297/59677941-b7540100-91fd-11e9-9b7a-688e88850afd.png)

**Comment by plemarquand** [comment]
This bit me as well. Tracked back to https://github.com/davidbau/seedrandom/issues/64

**Comment by chrisrzhou** [comment]
@plemarquand thanks for tracking the issue to the source issue.  Seems like the PR is active there.  Once `seedrandom` is fixed, I'll merge the changes on my side and release `1.1.0` with the changes.  I have pushed a few code improvements to `master` and will wait for this fix before releasing `1.1.0`.

**Comment by chrisrzhou** [comment]
fixed in `v1.1.1` after `seedrandom@3.0.5` is shipped!
