### ISSUE TITLE
Wordcloud fully re-renders every time props change

### ISSUE THREAD

**Issue by camlough** [chrisrzhou/react-wordcloud#25]
Hello! Great job on this library. Very straight-forward to use, yet very powerful. 

I have been trying to use it for a real-time word cloud, where words will appear and disappear as i receive updated data from a websocket connection. My problem is the wordcloud does a full re-render every time the `words` prop (or any prop for that matter) is updated, which causes the whole thing to re-animate (see #1 gif below). If I set the `transitionDuration` to 0, then the whole thing flashes each time new data comes in.

After digging through this code-base I see the problem is here in the hooks.ts file:
``` 
useEffect(() => {
      .....
  }, [initialSize, minSize]);  <---- problem
```
Because the `initialSize` and `minSize` props are of type Array, React cannot do a comparison on them and must run this effect every time resulting in new `elementRef, selection, size` values. I have confirmed that the word cloud animates smoothly if i just pass an empty array as the second argument to that effect hook (see #2 gif below).

Is there any way to get around this? I understand this library was probably not designed with real-time updates in mind, but it would be great if it could support it. 

**1.) This is what the word cloud looks like when attempting to update with real-time data**:
![g5gSB8pals](https://user-images.githubusercontent.com/3344878/68630057-f3347f00-049a-11ea-835f-87a00af4a015.gif)

**2.) This is how it should look, without the full re-render**:
![AbE1nFj4vA](https://user-images.githubusercontent.com/3344878/68630394-13b10900-049c-11ea-8ca7-a45e94eaed60.gif)

**Comment by emorling** [comment]
Subscribe :) This merge would be really useful

**Comment by chrisrzhou** [comment]
I'll work on integrating @camlough's PR this weekend.

**Comment by flippyhead** [comment]
Hello! It looks like the above PR was approved. This would also be a great addition. Can it be merged? I'd be happy to help!

**Comment by chrisrzhou** [comment]
Hey guys, I wanted to provide an update that I didn't apply @camlough's fix.  The changes affect current APIs and after some careful thought, I prefer that the component behaves with default React behavior (i.e. changes in props will re-render the component).

I wrote some detailed section in [Common Issues](https://react-wordcloud.netlify.com/common-issues#re-rendering-issues) that talks about how this can be resolved.  You should define these prop values outside of the component or memoize it accordingly.  I know it's a slight inconvenience, but I wanted to remain unopinionated about how prop changes affect components and keep the mental model similar to default react. behaviors.

Thanks and hope the documentation helps!
