### ISSUE TITLE
Exaggerating the results

### ISSUE THREAD

**Issue by emorling** [chrisrzhou/react-wordcloud#27]
What settings do you recommend for exaggerating/contrasting the results, so that there is more of a "clear winner"? Even if there are small variations between the top 3 in terms of count. Obviously this could be achieved by maninpualting values, but I want to keep the values for the sake of tooltip. 

This image could help to illustrate what is desired to accomplish:
<img width="912" alt="Skärmavbild_2019-03-20_kl _20 29 45" src="https://user-images.githubusercontent.com/988266/69762687-4f6df300-116b-11ea-8b00-5155ad271054.png">

**Comment by chrisrzhou** [comment]
This should be customizable and a good suggestion! I'll look into exposing this through in a future update.  Let me know when is an ideal time you might need this feature by.
