### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by mathiashoeld** [chrisrzhou/react-wordcloud#31]
For some sets of words, there are problems while rendering the word cloud. The following warning is displayed in the console: 
```
Unable to layout 5 word(s) after 10 attempts.  Consider: (1) Increasing the container/component size. (2) Lowering the max font size. (3) Limiting the rotation angles.
```

and the display of the wordcloud is not correct (see image)
![image](https://user-images.githubusercontent.com/5782753/72525644-eea69100-3864-11ea-9752-9ffd43c8ecce.png)

The following words have been used and are displaying the same behaviour on my local machine as well as the code sandbox: 
```
          words: [
            {
              text: "zahlungsdienstleister",
              value: "64",
            },
            {
              text: "artikel",
              value: "116",
            },
            {
              text: "eu",
              value: "108",
            },
            {
              text: "verordnung",
              value: "103",
            },
            {
              text: "richtlinie",
              value: "98",
            },
            {
              text: "mitgliedstaaten",
              value: "98",
            },
            {
              text: "informationen",
              value: "89",
            },
            {
              text: "vorschlag",
              value: "73",
            },
            {
              text: "kommission",
              value: "70",
            },
            {
              text: "gemäß",
              value: "61",
            },
          ],
```

Additional interesting behaviour: When the word cloud is done rendering, not only do the font sizes NOT match the ones set in the `options` object, but also the scale is inverted, i.e. the words with the highest value are the smallest and vice versa. 

Increasing the size of the SVG container by increasing the `size` prop (as suggested by the warning) is not only not a very viable option (since i cannot anticipate when this problem appears) and does not always help. 

You can check it out here: https://codesandbox.io/s/react-wordcloud-options-wo9cr

**Comment by mathiashoeld** [comment]
Interestingly, when the objects with value > 100 are changed to a value < 100, the issue does not exist anymore

**Comment by chrisrzhou** [comment]
Hi @mathiashoeld, this is a known issue and is unfortunately difficult to fix.  The `d3-cloud` algorithm isn't robust enough to detect autosizing based on the word values and viz container.  It takes in explicit values, so you need to find optimal values of `fontSizes`, `size` etc.  These are slightly documented here: https://react-wordcloud.netlify.com/faq

In the future, a better fix would be to solve for this formally and support dynamic sizing.  This is challenging and out of scope in the short term!  Let me know if configuring any of the other wordcloud properties help!

**Comment by mathiashoeld** [comment]
hi @chrisrzhou! thanks for the reply and the feedback. i understand that this issue is basically beyond the scope of the package, so i'll just go ahead and close the issue. 

if i find a workaround for this, i'll just post it here. 

thanks for the good work, for the rest of my cases the wordcloud generator is working perfectly! really appreciate the effort.
