### ISSUE TITLE
Wordcloud Generator not working

### ISSUE THREAD

**Issue by mathiashoeld** [chrisrzhou/react-wordcloud#32]
In the section [Wordcloud Generator](https://github.com/chrisrzhou/react-wordcloud#wordcloud-generator) there is a link to an application that should generate wordclouds. When clicking on it, the page just displays "Not found"

**Comment by chrisrzhou** [comment]
Hi @mathiashoeld, I haven't had time to update that project yet, but thanks for the flag :) Will comment and close the issue once it's fully updated!

**Comment by chrisrzhou** [comment]
Hey @mathiashoeld, I spent a week building a fun/lightweight version of this.  Feel free to check it out here: https://wordcloud-generator.netlify.app/#
