### ISSUE TITLE
Preserve previous layout of cloud after render

### ISSUE THREAD

**Issue by CSchnars13** [chrisrzhou/react-wordcloud#38]
I want to write some functionality to always have the selected word be a special color in the cloud. To do this, I am making use of the `onWordClick` and `getWordColor` callbacks. The issue is, the cloud must rerender to update the colors but it scrambles the layout. Is it possible to preserve the previous layout (or achieve this in another way)?

**Comment by chrisrzhou** [comment]
Hi, try using `options.deterministic = true` configuration.  Let me know

**Comment by CSchnars13** [comment]
That plus setting the transition time to 0 solved the issue. Thanks!
