### ISSUE TITLE
Tooltip bug when page height bigger than viewport

### ISSUE THREAD

**Issue by pitops** [chrisrzhou/react-wordcloud#4]
I am using the default example provided but I had used it as a component in dashboard. However I discovered that the tooltip was not showing and from some quick debugging it seems the 'top' property was calculated wrong hence was overflowing.

To reproduce you need to put elements on top this component so that its pushed down and its not shown in viewport

From the source code

I dont see this function being used anywhere?

```javascript
_updatePosition = (currentX: number, currentY: number): void => {
    const {offsetHeight, offsetWidth} = this._container;
    const maxX = Math.min(window.innerWidth - offsetWidth, currentX);
    const maxY = Math.min(window.innerHeight - offsetHeight, currentY);
    if (maxX !== currentX || maxY !== currentY) {
      this.setState({
        x: maxX,
        y: maxY,
      });
    }
  };
```

If this function is called, then you should use `this._container.offsetTop` as the Y value

**Comment by pitops** [comment]
If anyone cares seem my last commit on my fork for the fix

```bash
https://github.com/pitops/react-wordcloud
```

**Comment by chrisrzhou** [comment]
This should be solved with `v1` release using `tippy.js`.  Thanks @pitops for debugging the old version!  Let me know if they work out for you!
