### ISSUE TITLE
Please document the `scale` and `spiral` options

### ISSUE THREAD

**Issue by dandv** [chrisrzhou/react-wordcloud#42]
At https://react-wordcloud.netlify.com/props#options:

[scale](https://github.com/chrisrzhou/react-wordcloud/blob/master/src/types.d.ts#L87) - "Control how words are spaced and laid out." - how exactly?

Same for [`spiral`](https://github.com/chrisrzhou/react-wordcloud/blob/master/src/types.d.ts#L93) - how should one think of `archimedean` vs. `rectangular`?

I'm trying to produce a 90-degree layout like this, but can't tell how to configure those options.

![image](https://user-images.githubusercontent.com/33569/77582168-cf527100-6f43-11ea-9607-cb6dbda8b60d.png)

A compact all-horizontal one would be fine too:

![image](https://user-images.githubusercontent.com/33569/77582236-ee510300-6f43-11ea-9bd8-f5d94618b0f0.png)

Words are very spaced out though.

**Comment by chrisrzhou** [comment]
Thanks for the feedback!

To be honest with you, I'm not sure how to describe `archimedean` and `rectangular` (source reference: https://www.jasondavies.com/wordcloud/).  I think it's a mathematical pattern of laying out the spiral and is somewhat visually noticeable.  When first working on this project, I was implementing features based on Jason Davies' wordcloud generator and kept this feature.  If there's a formal definition for this `prop`, I would totally be happy to update the `Props` page lol.

But to get to the two layouts you need, you should use `rotationAngles` and `rotations`
- https://codesandbox.io/s/react-wordcloud-options-kuswu?file=/src/index.js
- https://codesandbox.io/s/react-wordcloud-options-5qnqs?file=/src/index.js

It's covered super sparsely in https://react-wordcloud.netlify.app/usage/options#rotations, and I'll update the docs to include examples of these common layouts.  The way to think about it is: *The number of rotations I can use between specified min/max rotation angles*.

**Comment by chrisrzhou** [comment]
![image](https://user-images.githubusercontent.com/4425362/79837503-64d7f980-8366-11ea-9d7b-ee15cc549ad5.png)

Closing issues as docs will be updated based on feedback in this issue.  Thanks!
