### ISSUE TITLE
When use 'Mouse Events' it show me 'select' is not defined

### ISSUE THREAD

**Issue by zy87302728** [chrisrzhou/react-wordcloud#43]
https://react-wordcloud.netlify.com/usage/callbacks

'select' is not defined

**Comment by solirpa** [comment]
Its depends on the d3-selection

**Comment by chrisrzhou** [comment]
Can you reproduce what you're seeing in a codesandbox?  Here is the official Callbacks example in a codesandbox that you can test and try out: https://codesandbox.io/s/4lecp

There's a bug if (but that's specific to the example) if you hover over the words too fast before they are loaded, so for this example, wait for the loads to load up before hovering.

Leaving the issue open for 1-2 more weeks before closing just to make sure it's not a real bug!
