### ISSUE TITLE
Wordcloud implodes with high numbers of words

### ISSUE THREAD

**Issue by webisteme** [chrisrzhou/react-wordcloud#5]
The upper bound of fontScale's range is always 100, regardless of how many words are displayed or the size of the SVG canvas. This leads to intermittent collisions between words at high volumes (> 150). As a solution, I suggest setting the upper bound dynamically based on the ratio between the number of words and the SVG area size. This should allow the package to render large numbers of words without collisions by adjusting the fonts size dynamically. I will submit a Pull request if you are interested (and also if you are not).

**Comment by chrisrzhou** [comment]
@webisteme, awesome please feel free to submit a PR!  I plan to revisit and modernize this component in March when I find some time.

Thanks for debugging it and finding a fix for it!

**Comment by chrisrzhou** [comment]
Should be fixed to some extent for now.
