### ISSUE TITLE
Documentation site is out of date

### ISSUE THREAD

**Issue by davidjb** [chrisrzhou/react-wordcloud#56]
I was just looking at the documentation site at https://react-wordcloud.netlify.app and noticed that it's showing the docs for 1.2.3.  I'm not sure if this is related to the rename of the `main` branch, but thought it might be the cause if Netlify happens to be still pointing at `master` or needs a nudge otherwise.

**Comment by chrisrzhou** [comment]
Thanks for reporting, and fixed!  You are right that the branch was not pointing to `main`, but there was another issue where Netlify was using `v13.*` for `node`, and `docz`/`gatsby` builds have some issues with `v13.*`.  Added a `.node-version` file that points to `v14.*` and that helped fix the documentation issue.
