### ISSUE TITLE
v1.2.5 doesn't export typescript typings

### ISSUE THREAD

**Issue by SrividyaKK** [chrisrzhou/react-wordcloud#58]
I was running v1.2.3 of react-wordcloud. I updated to v1.2.5 and found that my builds failed, because it couldn't find the typescript typings. 

Upon inspection, I found that in v1.2.3, there was an `src` folder that had the typescript definitions `.d.ts` files, which are absent in v1.2.5.

**Comment by LeandroDG** [comment]
I was coming here to report the same issue. Thanks for the efforts, great work with the library :-)

**Comment by chrisrzhou** [comment]
I used `microbundle` for `v1.2.5` and `typings` *should* work but thanks for the bug report.  Will update, fix, and confirm this soon!

**Comment by chrisrzhou** [comment]
Tested and fixed in `v1.2.6`.  I was pointing to the wrong type files in `src`.  Apologies for the inconvenience since I'm getting familiarized with shipping packages!

**Comment by SrividyaKK** [comment]
Thank you! Great work with the library 👍  :-)
