### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brandoncc** [chrisrzhou/react-wordcloud#77]
Hello,

Thanks for this awesome library!

I am interested in using this in a commercial application, but there is no license. Would it be possible for one to be added?

Thank you!

**Comment by adrien-poirson** [comment]
There is one already: https://github.com/chrisrzhou/react-wordcloud/blob/main/license

**Comment by brandoncc** [comment]
I don't know how I missed that, thanks @adrienpwd !
