### ISSUE TITLE
How can I set orientation angles?

### ISSUE THREAD

**Issue by zerobell-lee** [chrisrzhou/react-wordcloud#8]
I'm researching WordCloud Generator, but I have no idea how I can set orientation angles. I guessed which properties available by opening WordCloud.js of WordCloud Generator. But there weren't enough explanations of properties. I hope I see which properties available when I handle with react-wordcloud, not only existence of properties, but also which types should be accepted.

I tried [-60, 60] for orientation angles, but it didn't work. How should I put value of orientation angles?

Thank you for your great project.

**Comment by chrisrzhou** [comment]
Hi, the Wordcloud generator is not actually using the current `react-wordcloud` code.  I just updated this to `v1.0.0`.  I will be updating the wordcloud generator example soon and sorry for the confusion!

For now, with v1.0.0, you should be able to set orientations in the `options` prop.  E.g.

```js
import ReactWordcloud from 'react-wordcloud';

<ReactWordcloud
  options={{rotationAngles: [-90, 90]}}
  words={words}
/>
```

Here's an example on how to configure the wordcloud: https://github.com/chrisrzhou/react-wordcloud/blob/master/src/index.tsx#L17-L30

**Comment by zerobell-lee** [comment]
Thank you! It still doesn't work and I think maybe this bug occurred from that I used multiple wordcloud components in one page. But now I know how to set the options of ReactWordcloud. I'll test it with different configuration. Thank you for supporting!

**Comment by zerobell-lee** [comment]
Oh, I don't know why but when I try again home, it works! Thank you!
